version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nest-server
    command: npm run start:dev
    volumes:
    - ./server/:/usr/src/app
    - /usr/src/app/node_modules
    ports:
    - "5000:5000"
    depends_on:
    - mongo
    networks:
    - app-network
  mongo:
    image: mongo
    volumes:
    - data-volume:/data/db
    ports:
    - "27017:27017"
    networks:
    - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-client
    command: npm start
    volumes:
    - ./client/:/usr/src/app
    - /usr/src/app/node_modules
    depends_on:
    - server
    ports:
    - "3000:3000"
    networks:
    - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
